version: '3'
services:
  db:
    container_name: vidstor-postgres
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_PASSWORD=odoo_db_pass
    - POSTGRES_USER=odoo
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ../db_files:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
  adminer:
    image: adminer:4.6
    container_name: vidstor-adminer
    restart: always
    depends_on:
    - db
    ports:
    - "8080:8080"
